---
resource_types:
  - name: travis
    type: docker-image
    source:
      repository: rbakergds/travis-resource
      tag: latest

resources:
  - name: govuk-coronavirus-find-support
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-coronavirus-find-support
      branch: master

  - name: git-tests-image-deps
    icon: github-circle
    type: git
    source:
      uri:  https://github.com/alphagov/govuk-coronavirus-find-support
      branch: master
      paths:
        - features/Dockerfile
        - Gemfile
        - Gemfile.lock

  - name: govuk-coronavirus-find-support-feature-tests
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-coronavirus-find-support
      branch: master
      paths:
        - Gemfile*
        - .ruby-version
        - features/

  - name: every-day
    type: time
    source:
      interval: 24h

  - name: govuk-coronavirus-find-support-travis-build
    type: travis
    icon: sync
    source:
      repository: alphagov/govuk-coronavirus-find-support
      travis-token: ((travis-api-token))
      branch: master
      pro: true

  - name: feature-tests-image
    type: docker-image
    icon: docker
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: govuk-coronavirus-find-support-feature-tests

  - name: tests-image
    type: docker-image
    icon: docker
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: govuk-coronavirus-find-support-tests

jobs:
  - name: update-pipeline
    plan:
      - get: govuk-coronavirus-find-support
        trigger: true
      - set_pipeline: govuk-corona-find-support-form
        file: govuk-coronavirus-find-support/concourse/pipeline.yml

  - name: build-tests-image
    serial: true
    build_logs_to_retain: 100
    plan:
      - get: git-tests-image-deps
        trigger: true
      - put: tests-image
        params:
          build: git-tests-image-deps
          dockerfile: git-tests-image-deps/features/Dockerfile

  - name: run-quality-checks
    plan:
      - in_parallel:
        - get: tests-image
          passed:
            - build-tests-image
        - get: govuk-coronavirus-find-support
          trigger: true
      - task: run-tests-task
        image: tests-image
        config:
          inputs:
            - name: govuk-coronavirus-find-support
          outputs:
            - name: committer-details
          platform: linux
          run:
            dir: govuk-coronavirus-find-support
            path: bash
            args:
              - -c
              - |
                set -ue
                cat .git/committer > ../committer-details/last-committer
                postgres -p 5432 -D /usr/local/var/postgres >&1 &
                bundle exec rake

  - name: build-feature-tests-image
    serial: true
    plan:
      - get: every-day
        trigger: true
      - get: govuk-coronavirus-find-support-feature-tests
        trigger: true
      - put: feature-tests-image
        params:
          build: govuk-coronavirus-find-support-feature-tests
          dockerfile: govuk-coronavirus-find-support-feature-tests/features/Dockerfile

  - name: deploy-to-staging
    serial: true
    plan:
      - get: govuk-coronavirus-find-support-travis-build
        trigger: true
      - get: govuk-coronavirus-find-support
      - task: deploy-to-paas
        config:
        file: govuk-coronavirus-find-support/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: staging
          INSTANCES: 5
          CF_STARTUP_TIMEOUT: 5 # minutes
          REQUIRE_BASIC_AUTH: "true"
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          AWS_ACCESS_KEY_ID: ((aws-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
          SECRET_KEY_BASE: ((secret-key-base-staging))
          AWS_ASSETS_BUCKET_NAME: govuk-coronavirus-find-support-assets-staging
          HOSTNAME: govuk-coronavirus-find-support-stg

  - name: smoke-test-staging
    plan:
      - get: govuk-coronavirus-find-support
        trigger: true
        passed: [deploy-to-staging]
      - task: smoke-test
        file: govuk-coronavirus-find-support/concourse/tasks/smoke-test.yml
        params:
          URL: 'https://govuk-coronavirus-find-support-stg.cloudapps.digital/urgent-medical-help'
          MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
      #- task: run-cucumber-specs
      #  file: govuk-coronavirus-find-support/concourse/tasks/run-cucumber-specs.yml
      #  params:
      #    TEST_URL: 'https://gds:((basic-auth-password))@govuk-coronavirus-find-support-stg.cloudapps.digital'

  - name: deploy-to-prod
    serial: true
    plan:
      - get: govuk-coronavirus-find-support
        trigger: true
        passed: [smoke-test-staging]
      - task: deploy-to-paas
        file: govuk-coronavirus-find-support/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: production
          INSTANCES: 30
          CF_STARTUP_TIMEOUT: 15 # minutes
          REQUIRE_BASIC_AUTH:
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          AWS_ACCESS_KEY_ID: ((aws-access-key-id-prod))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key-prod))
          SECRET_KEY_BASE: ((secret-key-base-prod))
          AWS_ASSETS_BUCKET_NAME: govuk-coronavirus-find-support-assets-prod
          HOSTNAME: govuk-coronavirus-find-support-prod

  - name: smoke-test-prod
    serial: true
    plan:
      - get: govuk-coronavirus-find-support
        trigger: true
        passed: [deploy-to-prod]
      - task: smoke-test
        file: govuk-coronavirus-find-support/concourse/tasks/smoke-test.yml
        timeout: 5m
        params:
          # TODO: this should point at the production URL
          URL: 'https://govuk-coronavirus-find-support-prod.cloudapps.digital/urgent-medical-help'
          MESSAGE: "Checks that the application deployed to production is not serving HTTP error codes. If this fails, you should investigate immediately."
