platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: govuk-coronavirus-find-support-feature-tests
params:
  TEST_URL:
inputs:
  - name: govuk-coronavirus-find-support
run:
  path: rails
  dir: govuk-coronavirus-find-support
  args: ['cucumber']
