platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: govuk-coronavirus-find-support-feature-tests
params:
  TEST_URL:
  RAILS_ENV: smoke_test
inputs:
  - name: git-master
run:
  path: bundle
  dir: git-master
  args: ['exec', 'rspec', 'spec/features']
