on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle

    - run: sudo apt-get -yqq install libpq-dev
    - run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake db:create
        bundle exec rake db:migrate
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        DB_USERNAME: postgres

    - run: |
        bundle exec rake
        bundle exec rake spec:javascript
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        DB_USERNAME: postgres
